### ISSUE TITLE
Write to Excel file with OpenPyXL

### ISSUE THREAD

**Issue by ssatosays** [ssatosays/issue-based-blog#2]
```python
from openpyxl import load_workbook

filename = 'target.xlsx'
workbook = load_workbook(filename)

worksheet = workbook['Sheet1']

worksheet['A1'] = 'a'
worksheet['B1'] = 'b'
worksheet['C1'] = 'c'

workbook.save(filename)
```

**Comment by Dubist149** [comment]
Hi  
I have a question regarding "from openpyxl import workbook".  My coding (for Python) is quite similar to yours as above, 
but the output indicated that zsh: no matches found: excel-read(1).xlsx. I have checked the filename in my computer, and it is correct. Besides, I also checked the path of the file in the computer. It is correct. 
But the results makes me stop the coding. I am really confused. Do you know the reason why and can you help with this ? 

-----------------------------------------------------------------------------
import openpyxl import Workbook, load_workbook 

wb = load_workbookk("C:/Users/vera.chen886/Desktop/excel.py/STEAM excel-read(1).xlsx")
sheet = wb.active 
cell_value = sheet["A1"].value
print(cell_value)

zsh: no matches found: excel-read(1).xlsx 

------------------------------------------------------------------------------

**Comment by Dubist149** [comment]
Hi,  I re-downloaded VS Code and changed some settings. 
The original code: 
wb = load_workbookk("C:/Users/vera.chen886/Desktop/excel.py/STEAM excel-read(1).xlsx") 
I removed C: and revised it as below and then, it works now. 
wb = load_workbook('/Users/vera.chen886/Desktop/new_excel.xlsx')
Also, thanks for your advice.

**Comment by Dubist149** [comment]
@ssatosays 
Hi, I re-downloaded VS Code and changed some settings.
The original code:
wb = load_workbookk("C:/Users/vera.chen886/Desktop/excel.py/STEAM excel-read(1).xlsx")

I removed C: and revised it as below and then, it works now.
wb = load_workbook('/Users/vera.chen886/Desktop/STEAM excel-read(1).xlsx')

> load_workbook
('/Users/vera.chen886/Desktop/STEAM excel-read(1).xlsx')
Also, thanks for your advice.
